name: "Dependabot Automerge - Action"

on:
  workflow_dispatch:

jobs:
  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request by GitHub-Actions bot
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.client_payload.PullRequestNumber }},
              event: "APPROVE"
            });
      - name: Merge pull request for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.client_payload.PullRequestNumber }},
              merge_method: "squash"
            })