name: "Dependabot Automerge - Action"

on:
  workflow_dispatch:

jobs:
  Merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Approve pull request by GitHub-Actions bot
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: "APPROVE"
            });